sudo: required
services:
  - docker

before_install:
  - docker build -t diovanavalim/fibonacci-sequence-frontend -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true diovanavalim/fibonacci-sequence-frontend npm test

after_success:
  - docker build -t diovanavalim/fibonacci-sequence-client ./client
  - docker build -t diovanavalim/fibonacci-sequence-nginx ./nginx
  - docker build -t diovanavalim/fibonacci-sequence-server ./server
  - docker build -t diovanavalim/fibonacci-sequence-worker ./worker
  # Login to Docker CLI to publish this images
  - docker login -u $DOCKER_ID -p $DOCKER_PASSWORD
  # Push images to docker hub
  - docker push diovanavalim/fibonacci-sequence-client:latest
  - docker push diovanavalim/fibonacci-sequence-nginx:latest
  - docker push diovanavalim/fibonacci-sequence-server:latest
  - docker push diovanavalim/fibonacci-sequence-worker:latest

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: 'fibonacci-sequence'
  env: 'Fibonaccisequence-env'
  bucket_name: elasticbeanstalk-us-east-2-169301003861 
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY