sudo: required
services:
  - docker

before_install:
  - docker build -t ddvalim/fibonacci-sequence-frontend -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ddvalim/fibonacci-sequence-frontend npm test

after_success:
  - docker build -t ddvalim/fibonacci-sequence-client ./client
  - docker build -t ddvalim/fibonacci-sequence-nginx ./nginx
  - docker build -t ddvalim/fibonacci-sequence-server ./server
  - docker build -t ddvalim/fibonacci-sequence-worker ./worker
  # Login to Docker CLI to publish this images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push ddvalim/fibonacci-sequence-client
  - docker push ddvalim/fibonacci-sequence-nginx
  - docker push ddvalim/fibonacci-sequence-server
  - docker push ddvalim/fibonacci-sequence-worker